# Generated by Django 2.0 on 2017-12-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_share_price_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SAL', 'Sale'), ('REI', 'Reinvestment'), ('RED', 'Redemption'), ('DPF', 'Depot Fee')], default='BUY', max_length=3)),
                ('transaction_date', models.DateField()),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_of_order',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='order_exchange_rate',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='order_price_currency',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='shares',
        ),
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Investment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='share_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.SharePrice'),
        ),
        migrations.AddField(
            model_name='investment',
            name='portfolio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='portfolio.Portfolio'),
        ),
    ]
