# Generated by Django 2.0 on 2017-12-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_asset_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cusip',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='asset',
            name='valor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='wkn',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='bond',
            name='funds',
            field=models.ManyToManyField(blank=True, to='portfolio.Fund'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='funds',
            field=models.ManyToManyField(blank=True, to='portfolio.Fund'),
        ),
    ]
